stages:
  - build
  - push    
    
docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_TOKEN}
  script:
    - echo "Generating image ${DOCKER_USER}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}..."
    - docker build -t ${DOCKER_USER}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG} .
  # Run this job in a branch where a Dockerfile exists
  rules:
    - if: $CI_COMMIT_TAG

docker-push:
  stage: push
  script:
    - echo "Pushing image ${DOCKER_USER}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}..."
    - docker push ${DOCKER_USER}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}
    - docker push ${DOCKER_USER}/${CI_PROJECT_NAME}
  rules:
    - if: $CI_COMMIT_TAG