stages:
  - build
  - push    
    
docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_PROJECT_NAMESPACE} -p ${DOCKER_TOKEN}
  script:
    - echo "Generating image ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${tag}..."
    - docker build -t ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${tag} .
  # Run this job in a branch where a Dockerfile exists
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile

docker-push:
  stage: push
  script:
    - echo "Pushing image ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${tag}..."
    - docker push ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${tag}
    - docker push ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}