stages:
  - build

variables:
  CONTAINER_REGISTRY: 'luisnabais/bind9'
  BUILDX_VERSION: "v0.12.1"
  BUILDX_URL: "https://github.com/docker/buildx/releases/download/${BUILDX_VERSION}/buildx-${BUILDX_VERSION}.linux-amd64"
  BUILDX_PLATFORMS: "linux/amd64,linux/arm64/v8"

container-build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - wget -O /usr/bin/docker-buildx ${BUILDX_URL}
    - chmod +x /usr/bin/docker-buildx
    - docker login -u ${DOCKER_USER} -p ${DOCKER_TOKEN}
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    - ALPINE_TAG=$(grep FROM Dockerfile | cut -d' ' -f2 | tr -d ':')
    - docker-buildx create --use
    - docker buildx build
      --provenance=false
      --platform ${BUILDX_PLATFORMS}
      --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}-${ALPINE_TAG}
      --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}-alpine
      --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
      --tag ${CI_REGISTRY_IMAGE}:alpine
      --tag ${CI_REGISTRY_IMAGE}:latest
      --tag ${CONTAINER_REGISTRY}:${CI_COMMIT_TAG}-${ALPINE_TAG}
      --tag ${CONTAINER_REGISTRY}:${CI_COMMIT_TAG}-alpine
      --tag ${CONTAINER_REGISTRY}:${CI_COMMIT_TAG}
      --tag ${CONTAINER_REGISTRY}:alpine
      --tag ${CONTAINER_REGISTRY}:latest
      --push
      .
  rules:
    - if: $CI_COMMIT_TAG